# Generated by Django 6.0.5 on 2026-05-19 15:26

import django.core.validators
import re
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "inn",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="INN must contain 10 or 12 digits",
                                regex="^(\\d{10}|\\d{12})$",
                            )
                        ],
                    ),
                ),
                ("contact_email", models.EmailField(max_length=200, unique=True)),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: +70000000000",
                                regex=re.compile("^(?:\\+7|8)?\\d{10}$"),
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
