# Generated by Django 6.0.5 on 2026-05-15 12:20

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="contact_phone",
            field=models.CharField(
                default=0,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: +70000000000",
                        regex=re.compile("^(?:\\+7|8)?\\d{10}$"),
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="inn",
            field=models.CharField(
                default=0,
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="INN must contain 10 or 12 digits",
                        regex="^(\\d{10}|\\d{12})$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="seller",
            name="contact_email",
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
