services:
  b2b-service:
    build:
      context: ./B2B
      dockerfile: Dockerfile
    container_name: neo-market-b2b-service
    command: uv run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    env_file:
      - ./B2B/.env
    volumes:
      - ./B2B:/usr/src/app
    depends_on:
      - b2b-db

  b2b-db:
    image: postgres:16
    container_name: neo-market-b2b-db
    env_file:
      - ./B2B/.env
    ports:
      - "5433:5432"
    volumes:
      - b2b_postgres_data:/var/lib/postgresql/data

volumes:
  b2b_postgres_data: