# Generated by Django 6.0.5 on 2026-05-19 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("MODERATION", "Moderation"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="CREATED",
                        max_length=50,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("blocking_reason_id", models.UUIDField(blank=True, null=True)),
                ("moderator_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="categories.category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="sellers.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCharacteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                ("ordering", models.PositiveBigIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status_from",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("MODERATION", "Moderation"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status_to",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("MODERATION", "Moderation"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=50,
                    ),
                ),
                ("changed_by", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
