# Generated by Django 6.0.5 on 2026-05-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('draft', 'Draft'), ('moderation', 'Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
    ]
