# Generated by Django 6.0.5 on 2026-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("ON_MODERATION", "On moderation"),
                    ("MODERATED", "Moderated"),
                    ("BLOCKED", "Blocked"),
                    ("HARD_BLOCKED", "Hard blocked"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                default="CREATED",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="productstatushistory",
            name="status_from",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("ON_MODERATION", "On moderation"),
                    ("MODERATED", "Moderated"),
                    ("BLOCKED", "Blocked"),
                    ("HARD_BLOCKED", "Hard blocked"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="productstatushistory",
            name="status_to",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("ON_MODERATION", "On moderation"),
                    ("MODERATED", "Moderated"),
                    ("BLOCKED", "Blocked"),
                    ("HARD_BLOCKED", "Hard blocked"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                max_length=50,
            ),
        ),
    ]
