# Generated by Codex on 2026-06-03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_status_and_more"),
        ("skus", "0003_skucharacteristics_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="blocking_reason_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="ProductFieldReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("description", "Description"),
                            ("product_images", "Product images"),
                            ("category", "Category"),
                            ("sku_name", "SKU name"),
                            ("sku_image", "SKU image"),
                            ("sku_price", "SKU price"),
                        ],
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_reports",
                        to="products.product",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_reports",
                        to="skus.sku",
                    ),
                ),
            ],
        ),
    ]
