# Generated by Codex on 2026-06-08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_blocking_reason_title_productfieldreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedModerationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "sender_service",
                    models.CharField(max_length=64),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        db_index=True,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("status", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sender_service", "idempotency_key"),
                        name="unique_processed_moderation_event",
                    )
                ],
            },
        ),
    ]
