# Generated by Django 6.0.5 on 2026-05-21 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skucharacteristics",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                to="skus.sku",
            ),
        ),
        migrations.CreateModel(
            name="SkuImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("ordering", models.IntegerField(default=0)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="skus.sku",
                    ),
                ),
            ],
        ),
    ]
